# Site settings
title: CV de Antoine Salesse
description: CV de Antoine Salesse
favicon: /assets/img/avatar.JPG
port: 8080
host: cv.antoine-salesse.fr
detach: true
baseurl: /fr

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Antoine Salesse
  title: Développeur Scrum Java
  address: Nantes, France
  email: contact@antoine-salesse.fr
  link: http://resume.antoine-salesse.fr
  github: t4w4n3
  linkedin: antoine-salesse-385318101
  stackoverflow:
  workHistory:
    - work1:
      company: Capgemini
      location: Nantes, France
      title: Développeur Scrum Java
      started: 2019
      duration: (2019 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: Sogeti
      location: Nantes, France
      title: Développeur shell, Java 7, PL/SQL
      started: 2016
      duration: (2016 - 2018)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: Bimedia
      location: La Roche-sur-Yon, France
      title: Développeur Node.js
      started: 2016
      duration: (avril 2016 - août 2016)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: ENSEIRB-MATMECA
      location: Bordeaux, France
      degree: Master en alternance
      major: Réseaux et Systèmes d'Information
      started: 2012
      duration: (2012 - 2015)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Francais
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Spanish
      proficiency: Long time ago
  programmingSkills:
    - skill1:
      name: Java SE 8
      percentage: 88%
    - skill2:
      name: Java EE 7
      percentage: 50%
    - skill3:
      name: Jax-RS
      percentage: 65%
